### ISSUE TITLE
Update `paysWithFeeOrigin?` optional input to be compatible with asset conversion tx payment pallet functionality.

### ISSUE THREAD

**Issue by IkerAlus** [paritytech/asset-transfer-api#228]
Currently, the `paysWithFeeOrigin?` optional input in Asset Transfer API uses the functionality enabled by the asset tx payment pallet to pay fees with sufficient assets in Asset Hub. However, the functionality to pay fees with other assets beyond DOT is going to be given by the [asset conversion tx payment pallet](https://github.com/paritytech/substrate/blob/master/frame/transaction-payment/asset-conversion-tx-payment/src/lib.rs) soon (it is already the case on Westend testnet). Hence the functionality of this input needs to be updated accordingly.

**Comment by IkerAlus** [comment]
At the moment, there is [a check for asset sufficiency](https://github.com/paritytech/asset-transfer-api/blob/5bb5729a48dc3651082fd05e867caa7543ab2f41/src/AssetsTransferApi.ts#L898), once the [asset conversion tx payment pallet](https://github.com/paritytech/substrate/blob/master/frame/transaction-payment/asset-conversion-tx-payment/src/lib.rs) is active on mainnet, this should be adapted to check if there is a liquidity pool of the asset, `assetID`, vs the relay chain token

**Comment by TarikGul** [comment]
This is mostly done via #338, we just need to check if there is a liquidity pool of the asset.

**Comment by IkerAlus** [comment]
@TarikGul @marshacb my understanding this is already fully supported, yes?

**Comment by TarikGul** [comment]
Yes this is completed and finished. @marshacb Added the final PR to wrap this up a while ago.
