### ISSUE TITLE
Foreign assets added to testnet script.

### ISSUE THREAD

**Issue by TarikGul** [paritytech/asset-transfer-api#253]
This requires that trappist has support for foreign assets so we can link an asset hub test chain to trappist via foreign assets.

**Comment by IkerAlus** [comment]
Not immediate, but this should be feasible now with this branch in trappist: https://github.com/paritytech/trappist/tree/polkadot-v0.9.43

Plus following the steps from 1 to 4 in this example: https://www.notion.so/paritytechnologies/Asset-Hub-integration-example-703eda72e22c4e1f8cda3c0350d6f3df

**Comment by TarikGul** [comment]
Awesome thanks so much for the links. I'll try this out today and get this going!
