### ISSUE TITLE
AccountKey20 support for Xtokens?

### ISSUE THREAD

**Issue by TarikGul** [paritytech/asset-transfer-api#307]
@marshacb We should probably give AccountKey20 support for all Xtokens and their applicable directions. Similar to how we handle it for Beneficiaries. 

Let me know what you think.

**Comment by marshacb** [comment]
> @marshacb We should probably give AccountKey20 support for all Xtokens and their applicable directions. Similar to how we handle it for Beneficiaries.
> 
> Let me know what you think.

Agreed. Makes sense to do this

**Comment by TarikGul** [comment]
Completed via https://github.com/paritytech/asset-transfer-api/pull/315
