### ISSUE TITLE
Error when used in Browser / React App

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/asset-transfer-api#337]
When embedding this project into a simple React Application, I get the following error when trying to construct a transaction:

`Status: Error: Error.captureStackTrace is not a function`

Some quick googling seems to imply this might be due to some libraries which are not intended to work inside the browser.

Is this the case?

**Comment by TarikGul** [comment]
Closing this in favor of #338, Browser support will be included in v0.1.6
