### ISSUE TITLE
[Tracking]: Migration from Rococo to Paseo

### ISSUE THREAD

**Issue by TarikGul** [paritytech/asset-transfer-api#354]
There are a few places to keep an eye out for this migration:

- Our zombienet scripts use rococo.
- Our registry has support for rococo.
- Any relay chain support in the ATA includes rococo.

**Comment by TarikGul** [comment]
This forum post is good to key an eye on: https://forum.polkadot.network/t/the-new-polkadot-community-testnet/4956/21

**Comment by IkerAlus** [comment]
With Asset hub and several other parachains live and running on Paseo testnet, we should consider adding support working on this issue soon.

**Comment by IkerAlus** [comment]
We have concrete plan and dates to deprecate Rococo: https://forum.polkadot.network/t/rococo-to-be-deprecated-in-october/8702
