### ISSUE TITLE
Injected registry should allow for overriding and deep comparison

### ISSUE THREAD

**Issue by TarikGul** [paritytech/asset-transfer-api#357]
Currently the `injectedRegsitry` option just allows for adding in a chain based on ID. But it actually doesn't do any deep comparison.

Example:

If the registry contains

```
polkadot: {
    '9876': {
        tokens: ['TST'],
	assetsInfo: { ... },
	foreignAssetsInfo: { ... },
	specName: 'testing',
	poolPairsInfo: { ... },
    },
},
```

The user should be able to input:

```
injectedRegistry: {
    polkadot: {
        '9876': {
            tokens: ['TST', 'TST2']
        }
    }
}
```

Which will only update the tokens field with the new values. This should be applicable to any field in the registry.

**Comment by bee344** [comment]
This is partially covered by #359 , which covers the update and deep comparison. The overriding is still pending

**Comment by TarikGul** [comment]
Completed via: https://github.com/paritytech/asset-transfer-api/pull/369
