### ISSUE TITLE
Update assetId to handle a hexString

### ISSUE THREAD

**Issue by IkerAlus** [paritytech/asset-transfer-api#430]
Ref: https://github.com/polkadot-js/api/pull/5967

Once a the new version of PJS/Api is released, it will come with a breaking change of handling the assetId as a HexString instead of number | object as it's now. The dep will have to be updated as well as the corresponding methods/examples/tests that currently handle that field.

**Comment by marshacb** [comment]
Due to Asset Transfer API not relying on the `SignerPayloadJSON` interface directly from PJS, the `assetId` `HexString` update made in https://github.com/polkadot-js/api/pull/5967 does not require any additional changes in the API.
