### ISSUE TITLE
Investigating a different return value for `createTransferTransaction`

### ISSUE THREAD

**Issue by TarikGul** [paritytech/asset-transfer-api#73]
Currently `createTransferTransaction` 3 different values in 2 formats depending on the `format` option. The options are `call`, `payload`, and `submittable`. Either a hex will be returned or a polkadot-js Submittable type.

This has been on my mind since designing and implementing the API, but to make errors clearing and following a more `rust` like syntax return a `Result`, that either has the return value or an error attached. Along with that should we change that return value to be a object with the following metadata attached:

If the `Result` is `ok`, it would need to be unwrapped using `unwrap`.
```
{
    xcmVersion: string,
    direction: This will be the xcmDirection or local for a local transaction.
    result: (This will be the call payload or submittable)
}
```

If the `Result` is an `err`, it would have the following structure:
{
    type: The type of error this is
    msg: The error message. 
}

Open to adding more information as well.

@IkerAlus Curious on your thoughts.

**Comment by IkerAlus** [comment]
In my opinion the main points to consider here are:

- is this pattern well understood by the expected average user of the API (JS/TS dev)? If not, how big is the effort/ extra work required to understand it?
- Assuming `createTransferTransaction` function is going to be used in a script together with other code to create, sign and/or submit the extrinsic: Is this patter going to introduce "unnecessary steps"  or can this workflow be easily automated?

**Comment by TarikGul** [comment]
Given the above it's best to iterate over this slowly. I merged in the first iteration that basically changes the structure of the return value. https://github.com/paritytech/asset-transfer-api/pull/85

It just provides some meta information about that transaction. In terms of if we should add `Result` or not. We can discuss that further.

**Comment by TarikGul** [comment]
Closing due to conversations in the team. The return value currently is acceptable, and enough for logging, and debugging.
